<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('edu_turma_aluno_situacao', function (Blueprint $table) {
            $table->smallInteger('tas_cod')->primary();
            $table->string('tas_descricao', 60);
            $table->string('tas_descricao_boletim', 60);
            $table->string('tas_descricao_mapa', 60);
            $table->string('tas_descricao_enturmacao', 60);
            $table->char('tas_mostrar_boletim', 1)->default('N');
            $table->char('tas_mostrar_mapa', 1)->default('N');
            $table->char('tas_mostrar_enturmacao', 1)->default('N');
            $table->char('tas_possibilita_matricula', 1)->default('N');
            $table->text('tas_observacao')->nullable();
            $table->char('tas_modo', 1);
            $table->string('tas_enturmacao_modelo_i', 60)->nullable();
            $table->smallInteger('tas_ctrl_cod')->nullable();
        });

        DB::table('edu_turma_aluno_situacao')->insert([
            ['tas_cod' => 1,  'tas_descricao' => 'Novo',                          'tas_descricao_boletim' => 'Matriculado(a)',               'tas_descricao_mapa' => 'Matriculado(a)',               'tas_descricao_enturmacao' => 'Matriculado(a)',               'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'N', 'tas_observacao' => 'Situação atribuída ao aluno matriculado normalmente na turma, vindo de outra escola',                                                                                                              'tas_modo' => 'E', 'tas_enturmacao_modelo_i' => null,                    'tas_ctrl_cod' => 4],
            ['tas_cod' => 2,  'tas_descricao' => 'Desistente',                    'tas_descricao_boletim' => 'Desistente',                   'tas_descricao_mapa' => 'Desistente',                   'tas_descricao_enturmacao' => 'Desistente',                   'tas_mostrar_boletim' => 'N', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => 'Situação atribuida ao aluno que desiste(cancela) sua matrícula.',                                                                                                                          'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Desist. em',            'tas_ctrl_cod' => 3],
            ['tas_cod' => 3,  'tas_descricao' => 'Transferido(a)',                'tas_descricao_boletim' => 'Transferido(a)',               'tas_descricao_mapa' => 'Transferido(a)',               'tas_descricao_enturmacao' => 'Transferido(a)',               'tas_mostrar_boletim' => 'N', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => 'Situação atribuida ao aluno que pede transferencia para rede externa.',                                                                                                                  'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Transf. em',            'tas_ctrl_cod' => 3],
            ['tas_cod' => 4,  'tas_descricao' => 'Evadido(a)',                    'tas_descricao_boletim' => 'Evadido(a)',                   'tas_descricao_mapa' => 'Evadido(a)',                   'tas_descricao_enturmacao' => 'Evadido(a)',                   'tas_mostrar_boletim' => 'N', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => 'Situação atribuida ao aluno que evadiu da escola(45 dias consecutivos ausentes).',                                                                                                        'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Evad. em',              'tas_ctrl_cod' => 3],
            ['tas_cod' => 5,  'tas_descricao' => 'Óbito',                         'tas_descricao_boletim' => 'Óbito',                        'tas_descricao_mapa' => 'Óbito',                        'tas_descricao_enturmacao' => 'Óbito',                        'tas_mostrar_boletim' => 'N', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'N', 'tas_observacao' => 'Situação atribuida ao aluno que faleceu.',                                                                                                                                             'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Óbito em',              'tas_ctrl_cod' => 3],
            ['tas_cod' => 6,  'tas_descricao' => 'Aprovado (a)',                  'tas_descricao_boletim' => 'Aprovado (a)',                 'tas_descricao_mapa' => 'Aprovado(a)',                  'tas_descricao_enturmacao' => 'Aprovado (a)',                 'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => 'Situação atribuida ao aluno aprovado.',                                                                                                                                                'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Aprovado',              'tas_ctrl_cod' => 1],
            ['tas_cod' => 7,  'tas_descricao' => 'Apr. Conselho',                 'tas_descricao_boletim' => 'Apr. Conselho',                'tas_descricao_mapa' => 'Apr. Conselho',                'tas_descricao_enturmacao' => 'Apr. Conselho',                'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => 'Situação atribuida para o aluno que ficou reprovado por notas mas foi aprovado pelo conselho.',                                                                                            'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Aprovado pelo Conselho', 'tas_ctrl_cod' => 1],
            ['tas_cod' => 8,  'tas_descricao' => 'Aprovado pela Comissão',        'tas_descricao_boletim' => 'Aprovado pela Comissão',       'tas_descricao_mapa' => 'Aprovado pela Comissão',       'tas_descricao_enturmacao' => 'Aprovado pela Comissão',       'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => 'Situação atribuida ao aluno que ficou reprovado por faltas mas aprovado por notas e possui justificativa para as faltas, tornando-o aprovado.',                                            'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Aprovado pela Comissão', 'tas_ctrl_cod' => 1],
            ['tas_cod' => 9,  'tas_descricao' => 'Reprovado(a)',                  'tas_descricao_boletim' => 'Reprovado(a)',                 'tas_descricao_mapa' => 'Reprovado(a)',                 'tas_descricao_enturmacao' => 'Reprovado(a)',                 'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => 'Situação atribuida ao aluno que reprovou apenas por notas.',                                                                                                                          'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Reprovado por Nota',    'tas_ctrl_cod' => 2],
            ['tas_cod' => 10, 'tas_descricao' => 'Reprovado(a) por Falta',        'tas_descricao_boletim' => 'Reprovado(a)',                 'tas_descricao_mapa' => 'Reprovado(a)',                 'tas_descricao_enturmacao' => 'Reprovado(a)',                 'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => 'Situação atribuida ao aluno que reprovou apenas por faltas.',                                                                                                                         'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Reprovado por Falta',   'tas_ctrl_cod' => 2],
            ['tas_cod' => 11, 'tas_descricao' => 'Reprovado(a)',                  'tas_descricao_boletim' => 'Reprovado(a)',                 'tas_descricao_mapa' => 'Reprovado(a)',                 'tas_descricao_enturmacao' => 'Reprovado(a)',                 'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => 'Situação atribuida ao aluno que reprovou por faltas e por notas.',                                                                                                                    'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Reprovado por Falta',   'tas_ctrl_cod' => 2],
            ['tas_cod' => 12, 'tas_descricao' => 'Matricula - Classificado',      'tas_descricao_boletim' => 'Classificado(a)',              'tas_descricao_mapa' => 'Classificado(a)',              'tas_descricao_enturmacao' => 'Classificado(a)',              'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'N', 'tas_observacao' => 'Situação atribuida ao aluno que foi classificado. A classificação acontece quando um aluno que NUNCA estudou faz uma prova para verificar em qual série ele será encaixado.',            'tas_modo' => 'E', 'tas_enturmacao_modelo_i' => null,                    'tas_ctrl_cod' => 4],
            ['tas_cod' => 13, 'tas_descricao' => 'Reclassificado(a)',             'tas_descricao_boletim' => 'Reclassificado(a)',            'tas_descricao_mapa' => 'Reclassificado(a)',            'tas_descricao_enturmacao' => 'Reclassificado(a)',            'tas_mostrar_boletim' => 'N', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'N', 'tas_observacao' => 'Situação atribuida para o aluno que estudava em uma determinada série mas foi reclassificado para uma série seguinte. Esta situação se aplica à turma de origem.',              'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Reclassificado em',      'tas_ctrl_cod' => 3],
            ['tas_cod' => 14, 'tas_descricao' => 'Reclassificação',               'tas_descricao_boletim' => 'Reclassificação',              'tas_descricao_mapa' => 'Reclassificação',              'tas_descricao_enturmacao' => 'Reclassificação',              'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'N', 'tas_observacao' => 'Situação atribuida para o aluno que estudava em uma determinada série mas foi reclassificado para uma série seguinte. Esta situação se aplica à turma de destino.',            'tas_modo' => 'E', 'tas_enturmacao_modelo_i' => null,                    'tas_ctrl_cod' => 4],
            ['tas_cod' => 15, 'tas_descricao' => 'Remanejado(a)',                 'tas_descricao_boletim' => 'Remanejado(a)',                'tas_descricao_mapa' => 'Remanejado(a)',                'tas_descricao_enturmacao' => 'Remanejado(a)',                'tas_mostrar_boletim' => 'N', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => 'Situação atribuida ao aluno que saiu de uma turma com destino a outra, em uma mesma escola. Esta situação se aplica à turma de origem.',                                          'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Remanejado em',          'tas_ctrl_cod' => 3],
            ['tas_cod' => 16, 'tas_descricao' => 'Matricula - Remanejado',        'tas_descricao_boletim' => 'Matricula - Remanejado',       'tas_descricao_mapa' => 'Matricula - Remanejado',       'tas_descricao_enturmacao' => 'Matricula - Remanejado',       'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'N', 'tas_observacao' => 'Situação atribuida ao aluno que saiu de uma turma com destino a outra, em uma mesma escola. Esta situação se aplica à turma de destino.',                                         'tas_modo' => 'E', 'tas_enturmacao_modelo_i' => null,                    'tas_ctrl_cod' => 4],
            ['tas_cod' => 17, 'tas_descricao' => 'Renovado(a)',                   'tas_descricao_boletim' => 'Matriculado(a)',               'tas_descricao_mapa' => 'Matriculado(a)',               'tas_descricao_enturmacao' => 'Matriculado(a)',               'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'N', 'tas_observacao' => 'Situação atribuída ao aluno matriculado normalmente na turma, vindo de outra escola',                                                                                              'tas_modo' => 'E', 'tas_enturmacao_modelo_i' => null,                    'tas_ctrl_cod' => 4],
            ['tas_cod' => 18, 'tas_descricao' => 'Matricula - Transferido',       'tas_descricao_boletim' => 'Matriculado(a)',               'tas_descricao_mapa' => 'Matriculado(a)',               'tas_descricao_enturmacao' => 'Matriculado(a)',               'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'N', 'tas_observacao' => 'Situação atribuida ao aluno que é transferido de outra escola da rede. Esta situação se aplica à turma de origem.',                                                               'tas_modo' => 'E', 'tas_enturmacao_modelo_i' => null,                    'tas_ctrl_cod' => 4],
            ['tas_cod' => 19, 'tas_descricao' => 'Transferido Escola da Rede',    'tas_descricao_boletim' => 'Transferido(a)',               'tas_descricao_mapa' => 'Transferido(a)',               'tas_descricao_enturmacao' => 'Transferido(a)',               'tas_mostrar_boletim' => 'N', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'N', 'tas_observacao' => 'Situação atribuida ao aluno que é transferido de outra escola da rede. Esta situação se aplica à turma de destino.',                                                              'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Transferido em',        'tas_ctrl_cod' => 3],
            ['tas_cod' => 20, 'tas_descricao' => 'Matrícula Indevida',            'tas_descricao_boletim' => 'Matrícula Indevida',           'tas_descricao_mapa' => 'Matrícula Indevida',           'tas_descricao_enturmacao' => 'Matrícula Indevida',           'tas_mostrar_boletim' => 'N', 'tas_mostrar_mapa' => 'N', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => 'Situação atribuída ao alunos que matricularam-se em uma turma, foram para o diário mas nunca frequentaram à aula.',                                                               'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Mat.Indevida',           'tas_ctrl_cod' => 3],
            ['tas_cod' => 21, 'tas_descricao' => 'Inser. Automática',             'tas_descricao_boletim' => 'Inser. Automática',            'tas_descricao_mapa' => 'Inser. Automática',            'tas_descricao_enturmacao' => 'Inser. Automática',            'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => 'Situação atribuída ao alunos que tem a saída automática, não recebem aprovação e nem reprovação, essa situação é mais usada em creches.',                                         'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Inser. Automática',     'tas_ctrl_cod' => 1],
            ['tas_cod' => 22, 'tas_descricao' => 'Promovido(a)',                  'tas_descricao_boletim' => 'Promovido(a)',                 'tas_descricao_mapa' => 'Promovido(a)',                 'tas_descricao_enturmacao' => 'Promovido(a)',                 'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => 'Situação atribuída ao alunos que tem a saída automática, não recebem aprovação e nem reprovação, essa situação é mais usada em creches.',                                         'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Progre. Continuada',    'tas_ctrl_cod' => 1],
            ['tas_cod' => 23, 'tas_descricao' => 'Reprovado(a) por Relatório',    'tas_descricao_boletim' => 'Reprovado(a) por Relatório',   'tas_descricao_mapa' => 'Reprovado(a) por Relatório',   'tas_descricao_enturmacao' => 'Reprovado(a) por Relatório',   'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => 'Situação atribuida ao aluno que reprovou por relatório.',                                                                                                                        'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Reprovado por Relatório', 'tas_ctrl_cod' => 2],
            ['tas_cod' => 24, 'tas_descricao' => 'Repr. c/ Progre.Parcial',       'tas_descricao_boletim' => 'Repr. c/ Progre.Parcial',      'tas_descricao_mapa' => 'Repr. c/ Progre.Parcial',      'tas_descricao_enturmacao' => 'Repr. c/ Progre.Parcial',      'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => 'Situação atribuida ao aluno que reprovou com dependência.',                                                                                                                      'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Repr. c/ Progre.Parcial', 'tas_ctrl_cod' => 2],
            ['tas_cod' => 25, 'tas_descricao' => 'Progressão Continuada',         'tas_descricao_boletim' => 'Progressão Continuada',        'tas_descricao_mapa' => 'Progressão Continuada',        'tas_descricao_enturmacao' => 'Progressão Continuada',        'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => 'Situação atribuida ao aluno que aprovou com dependência.',                                                                                                                       'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Progressão Continuada', 'tas_ctrl_cod' => 1],
            ['tas_cod' => 26, 'tas_descricao' => 'Reprovado (a)',                  'tas_descricao_boletim' => 'Reprovado (a)',                'tas_descricao_mapa' => 'Reprovado (a)',                'tas_descricao_enturmacao' => 'Reprovado (a)',                'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => null,                                                                                                                                                                               'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => null,                    'tas_ctrl_cod' => 2],
            ['tas_cod' => 30, 'tas_descricao' => 'Matrícula Indeferida',          'tas_descricao_boletim' => 'Matrícula Indeferida',         'tas_descricao_mapa' => 'Matrícula Indeferida',         'tas_descricao_enturmacao' => 'Matrícula Indeferida',         'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => 'Situação atribuida ao aluno em abandono.',                                                                                                                                         'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Indeferida em',         'tas_ctrl_cod' => 3],
            ['tas_cod' => 31, 'tas_descricao' => 'Prova Final',                   'tas_descricao_boletim' => 'Prova Final',                  'tas_descricao_mapa' => 'Prova Final',                  'tas_descricao_enturmacao' => 'Prova Final',                  'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => 'Situação atribuida ao aluno que está de Prova Final.',                                                                                                                           'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Prova Final',           'tas_ctrl_cod' => null],
            ['tas_cod' => 32, 'tas_descricao' => 'Ava. por Relatório',            'tas_descricao_boletim' => 'Ava. por Relatório',           'tas_descricao_mapa' => 'Ava. por Relatório',           'tas_descricao_enturmacao' => 'Ava. por Relatório',           'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => 'Situação atribuida ao aluno avaliado por relatório.',                                                                                                                          'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Ava. por Relatório',   'tas_ctrl_cod' => 1],
            ['tas_cod' => 33, 'tas_descricao' => 'Ap. por Relatório',             'tas_descricao_boletim' => 'Ap. por Relatório',            'tas_descricao_mapa' => 'Ap. por Relatório',            'tas_descricao_enturmacao' => 'Ap. por Relatório',            'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => 'Situação atribuida ao aluno aprovado por relatório.',                                                                                                                          'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Ap. por Relatório',    'tas_ctrl_cod' => 1],
            ['tas_cod' => 34, 'tas_descricao' => 'Cancelamento de Matrícula',     'tas_descricao_boletim' => 'Matrícula Cancelada',          'tas_descricao_mapa' => 'Matrícula Cancelada',          'tas_descricao_enturmacao' => 'Matrícula Cancelada',          'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => 'Situação atribuido ao aluno que teve a matrícula cancelada pela Supervisora das Creches',                                                                                          'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Mat. Cancelada',        'tas_ctrl_cod' => 3],
            ['tas_cod' => 35, 'tas_descricao' => '__________',                    'tas_descricao_boletim' => '__________',                   'tas_descricao_mapa' => '__________',                   'tas_descricao_enturmacao' => '__________',                   'tas_mostrar_boletim' => 'N', 'tas_mostrar_mapa' => 'N', 'tas_mostrar_enturmacao' => 'N', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => 'Situação atribuída ao aluno que tem saída automática, não são aprovados nem reprovados. Essa situação é usada nas turmas de atividade complementar.',                              'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => '__________',             'tas_ctrl_cod' => 3],
            ['tas_cod' => 36, 'tas_descricao' => 'Trancamento de Matrícula',      'tas_descricao_boletim' => 'Tra. Matrícula',               'tas_descricao_mapa' => 'Tra. Matrícula',               'tas_descricao_enturmacao' => 'Tra. Matrícula',               'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => null,                                                                                                                                                                               'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Tra.Matrícula',         'tas_ctrl_cod' => 3],
            ['tas_cod' => 37, 'tas_descricao' => 'Retido(a)',                     'tas_descricao_boletim' => 'Retido(a)',                    'tas_descricao_mapa' => 'Retido(a)',                    'tas_descricao_enturmacao' => 'Retido(a)',                    'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => null,                                                                                                                                                                               'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Retido(a)',             'tas_ctrl_cod' => 2],
            ['tas_cod' => 38, 'tas_descricao' => 'Classificado',                  'tas_descricao_boletim' => 'Classificado',                 'tas_descricao_mapa' => 'Classificado',                 'tas_descricao_enturmacao' => 'Classificado',                 'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => null,                                                                                                                                                                               'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Classificado',          'tas_ctrl_cod' => 3],
            ['tas_cod' => 39, 'tas_descricao' => 'Deixou de Frequentar',          'tas_descricao_boletim' => 'Deixou de Frequentar',         'tas_descricao_mapa' => 'Deixou de Frequentar',         'tas_descricao_enturmacao' => 'Deixou de Frequentar',         'tas_mostrar_boletim' => 'N', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => 'Situação atribuida ao aluno que deixou de frequentar a escola',                                                                                                                   'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Evad. em',              'tas_ctrl_cod' => 3],
            ['tas_cod' => 40, 'tas_descricao' => 'Aprovado (a) com progressão parcial', 'tas_descricao_boletim' => 'Aprovado (a) com progressão parcial', 'tas_descricao_mapa' => 'Aprovado (a) com progressão parcial', 'tas_descricao_enturmacao' => 'Aprovado (a) com progressão parcial', 'tas_mostrar_boletim' => 'S', 'tas_mostrar_mapa' => 'S', 'tas_mostrar_enturmacao' => 'S', 'tas_possibilita_matricula' => 'S', 'tas_observacao' => 'Situação atribuida ao aluno aprovado em progressão parcial.',                                                                                   'tas_modo' => 'S', 'tas_enturmacao_modelo_i' => 'Aprovado',              'tas_ctrl_cod' => 1],
        ]);
    }

    public function down(): void
    {
        Schema::dropIfExists('edu_turma_aluno_situacao');
    }
};
