<?php

return [
    [
        'slug'      => 'parecer-descritivo',
        'titulo'    => 'Parecer Descritivo',
        'descricao' => 'Pareceres descritivos dos alunos de uma turma por período (bimestre/trimestre).',
        'categoria' => 'Diário',
        'grupo'     => 'diario',
        'icone'     => 'NotebookPen',
    ],
    [
        'slug'      => 'boletim',
        'titulo'    => 'Boletim do Aluno',
        'descricao' => 'Notas e conceitos por disciplina e período (ou consolidado), por aluno ou turma inteira.',
        'categoria' => 'Diário',
        'grupo'     => 'diario',
        'icone'     => 'GraduationCap',
    ],
    [
        'slug'      => 'mapa-notas',
        'titulo'    => 'Notas por Unidade',
        'descricao' => 'Quadro da turma com a média/conceito de cada aluno em todas as disciplinas, na unidade selecionada (ou consolidado).',
        'categoria' => 'Diário',
        'grupo'     => 'diario',
        'icone'     => 'Table',
    ],
    [
        'slug'      => 'boletim-avaliativo',
        'titulo'    => 'Boletim Avaliativo',
        'descricao' => 'Por disciplina da grade (1 página cada): todos os alunos com médias por bimestre, faltas na matéria, média final e resultado.',
        'categoria' => 'Diário',
        'grupo'     => 'diario',
        'icone'     => 'ClipboardList',
    ],
    [
        'slug'      => 'conteudo-ministrado',
        'titulo'    => 'Conteúdo Ministrado',
        'descricao' => 'Por disciplina, lista os dias com aula registrada, planejamento executado e o conteúdo/metodologia do dia.',
        'categoria' => 'Diário',
        'grupo'     => 'diario',
        'icone'     => 'BookOpenText',
    ],
    [
        'slug'      => 'frequencia-mensal',
        'titulo'    => 'Diário de Frequência Mensal',
        'descricao' => 'Frequência da turma em um mês: % e situação por aluno. F2/EJA por dias letivos; demais por aulas da turma.',
        'categoria' => 'Diário',
        'grupo'     => 'diario',
        'icone'     => 'CalendarCheck',
    ],
    [
        'slug'      => 'conteudo-ministrado-pedagogico',
        'titulo'    => 'Conteúdo Ministrado',
        'descricao' => 'Por disciplina, lista os dias com aula registrada, planejamento executado e o conteúdo/metodologia do dia.',
        'categoria' => 'Diário',
        'grupo'     => 'pedagogico',
        'icone'     => 'BookOpenText',
        'href'      => '/secretaria/conteudo-ministrado',
    ],
    [
        'slug'      => 'alunos-por-turma',
        'titulo'    => 'Alunos por Turma',
        'descricao' => 'Lista nominal com dados pessoais, situação e contato dos alunos por turma.',
        'categoria' => 'Aluno',
        'grupo'     => 'central',
        'icone'     => 'Users',
    ],
    [
        'slug'      => 'declaracao-matricula',
        'titulo'    => 'Declaração de Matrícula',
        'descricao' => 'Emite declaração de matrícula por aluno ou em lote por turma.',
        'categoria' => 'Aluno',
        'grupo'     => 'central',
        'icone'     => 'FileText',
    ],
    [
        'slug'      => 'formacao-classes',
        'titulo'    => 'Formação de Classes',
        'descricao' => 'Quadro de turmas com capacidade, expansão, alunos da rede, novos e vagas.',
        'categoria' => 'Turma',
        'grupo'     => 'central',
        'icone'     => 'LayoutGrid',
    ],
    [
        'slug'      => 'formacao-classes-aee',
        'titulo'    => 'Formação de Classes — AEE',
        'descricao' => 'Quadro de turmas AEE com capacidade, expansão, alunos da rede, novos e vagas.',
        'categoria' => 'Turma',
        'grupo'     => 'central',
        'icone'     => 'Accessibility',
    ],
    [
        'slug'      => 'sumario-matriculas',
        'titulo'    => 'Sumário de Matrículas',
        'descricao' => 'Total de matrículas REGULAR por escola e série.',
        'categoria' => 'Aluno',
        'grupo'     => 'central',
        'icone'     => 'Table',
    ],
    [
        'slug'      => 'ficha-matricula',
        'titulo'    => 'Ficha de Matrícula',
        'descricao' => 'Emite ficha completa de matrícula por aluno ou em lote por turma.',
        'categoria' => 'Aluno',
        'grupo'     => 'central',
        'icone'     => 'ClipboardList',
    ],
    [
        'slug'      => 'alunos-deficiencia',
        'titulo'    => 'Alunos com Deficiência',
        'descricao' => 'Lista de alunos PCD matriculados, agrupados por escola.',
        'categoria' => 'Aluno',
        'grupo'     => 'escola',
        'icone'     => 'Accessibility',
    ],
    [
        'slug'      => 'alunos-transtorno',
        'titulo'    => 'Alunos com Transtorno',
        'descricao' => 'Lista de alunos com TEA/TDAH/Dislexia/Disgrafia/Discalculia/Dislalia/TPAC. Indicadores por aluno.',
        'categoria' => 'Aluno',
        'grupo'     => 'escola',
        'icone'     => 'Brain',
    ],
    [
        'slug'      => 'dados-alunos-turma',
        'titulo'    => 'Dados de Alunos por Turma',
        'descricao' => 'Cadastro completo dos alunos por turma: documentos, filiação, endereço, etnia, idade.',
        'categoria' => 'Aluno',
        'grupo'     => 'escola',
        'icone'     => 'ClipboardList',
    ],
    [
        'slug'      => 'relacao-turmas-aee',
        'titulo'    => 'Relação de Turmas AEE',
        'descricao' => 'Lista de turmas AEE com INEP, escola, turno, dias de atendimento e quantidade de alunos.',
        'categoria' => 'Turma',
        'grupo'     => 'escola',
        'icone'     => 'Users',
    ],
    [
        'slug'      => 'desempenho-aee',
        'titulo'    => 'Desempenho AEE',
        'descricao' => 'Alunos das turmas AEE com suas avaliações descritivas registradas e a situação na turma.',
        'categoria' => 'Turma',
        'grupo'     => 'diario',
        'icone'     => 'Accessibility',
    ],
    [
        'slug'      => 'relacao-turmas-atividade',
        'titulo'    => 'Relação de Turmas de Atividade',
        'descricao' => 'Lista de turmas de atividade complementar com INEP, escola, turno, atividades, dias e qtd. de alunos.',
        'categoria' => 'Turma',
        'grupo'     => 'escola',
        'icone'     => 'Activity',
    ],
];
