export const PAISES: string[] = [
    'Brasil',
    'Argentina',
    'Bolívia',
    'Chile',
    'Colômbia',
    'Equador',
    'Paraguai',
    'Peru',
    'Uruguai',
    'Venezuela',
    'Estados Unidos',
    'Canadá',
    'México',
    'Cuba',
    'Haiti',
    'Portugal',
    'Espanha',
    'Itália',
    'França',
    'Alemanha',
    'Reino Unido',
    'Países Baixos',
    'Bélgica',
    'Suíça',
    'Polônia',
    'Ucrânia',
    'Rússia',
    'China',
    'Japão',
    'Coreia do Sul',
    'Índia',
    'Filipinas',
    'Síria',
    'Líbano',
    'Israel',
    'Angola',
    'Cabo Verde',
    'Moçambique',
    'Nigéria',
    'Senegal',
    'Outro',
];
